name: Slack Notification
on: [push]
jobs:
  notify:
    runs-on: ubuntu-latest
      github.base_ref == 'main' && github.event_name == 'action' }}
    steps:
    - name: Notify
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_WEBHOOK: ${{ secrets.https://hooks.slack.com/services/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 }}
        SLACK_CHANNEL: '#general'
        SLACK_MESSAGE: 'A push event 1 occurred on the repository.'
