name: Slack Notification

on:
  workflow_run:
    types: [completed]

jobs:
  slack-notification:
    if: ${{ github.event.workflow_run.event == 'workflow_run' && github.event.workflow_run.conclusion != 'skipped' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.https://hooks.slack.com/services/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 }}
          SLACK_USERNAME: "GitHub Actions"
          SLACK_ICON_EMOJI: ":rocket:"
          SLACK_MESSAGE: "Workflow *${{ github.event.workflow_run.workflow.name }}* has completed with status *${{ github.event.workflow_run.conclusion }}*"
